import styled from "styled-components";
import { createGlobalStyle } from "styled-components";
import Head from "next/head"

const GlobalStyle = createGlobalStyle`
    
    :root {
        --dark-cyan : #0E8784;
        --dark-grey-blue : #333d4b;
        --pale-orange : #fdd6ba;
        --light-cream : #fefc7;
        --grey : #83888F;
    }
    
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: 'Fraunces', 'Barlow', sans-serif , serif;
    }
`


const LayoutStyle = styled.div`
    width: 100%;
    height: 100%;
    background-color: var(--grey);
`


const Layout = ({children}) => {
    return (
        <LayoutStyle>
            <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="preconnect" href="https://fonts.googleapis.com" />
                    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                    <link href="https://fonts.googleapis.com/css2?family=Barlow&family=Fraunces:opsz,wght@9..144,400;9..144,900&display=swap" rel="stylesheet" /> 
            </Head>
            <GlobalStyle />
            
            {children}
        </LayoutStyle>
    );
}

export default Layout;
